FROM matthieujln/bird-sound-classif:base

WORKDIR /app

# Install curl
RUN apt-get update && apt-get install -y curl

# Development:
COPY ./requirements.txt .
RUN pip install -r requirements.txt


COPY . /app


# production:
# RUN pip install --no-cache-dir -r requirements.txt

RUN echo "alias python='python3'" >> /root/.bashrc

EXPOSE 8000

WORKDIR /app/api

#CMD ["uvicorn", "main:app", "--host=0.0.0.0" , "--reload" , "--port", "8000"]
